name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: Country
    attributes:
      label: country
      description: What country is this issue related to?
      options:
        - Colombia (COL)
        - Mexico (MEX)
        - Brasil (BRA)
        - India (IDN)
        - Indonesia (IND)
        - Pakistan (PAK)
        - Thailand (THA)
        - Zimbabwe (ZWE)
        - Chile (CHL)
        - Egypt (EGY)
        - Turkey (TUR)
        - South Africa (ZAR)
        - The Philippines (PHL)
        - Not country related (please elaborate in the box below)
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version are you seeing the problem on?
      multiple: true
      options:
        - V01
        - V02
        - V03
        - V04
        - Multiple (please explain in the log)
  - type: textarea
    id: year
    attributes:
      label: What year are you seeing the problem on?
      description: Please, specify the year(s) where the problem is present.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/worldbank/gld/blob/c3e0e28037247a64d7348824c9fdf03d142ad1d7/Support/E%20-%20Community%20Guidelines/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
