# Book settings
title: Global Labor Database
author: World Bank Jobs Group
logo: docs/images/WB_Jobs_logo_color.svg
only_build_toc_files: true

repository:
  url: https://github.com/worldbank/gld
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: true
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://worldbank.github.io/gld
  extra_footer: |
    <div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://opensource.org/license/mit/">MIT License.</a></b>
    </div>

#######################################################################################
# Execution settings
execute:
  execute_notebooks: "off"

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true # Allow display math ($$) within an inline context
